"""empty message

Revision ID: 6ab400c4661c
Revises: fe4b354e1e7f
Create Date: 2025-01-19 22:11:49.883905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ab400c4661c'
down_revision = 'fe4b354e1e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.drop_column('media_urls')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_urls', mysql.TEXT(), nullable=True))
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
